openapi: 3.1.0
info:
  version: '1.0'
  title: PatientController
servers:
  - url: 'http://localhost:9001'
paths:
  '/patients/{patientId}':
    get:
      summary: Get Patient Info by Patient ID
      description: Retrieve patient information with corresponding patient ID.
      operationId: get-patients-patientId
      parameters:
        - name: patientId
          in: path
          description: Patient ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      servers:
        - url: 'http://localhost:9001'
    patch:
      summary: Update Patient Information
      description: Update information for an existing patient.
      operationId: patch-patients-patientId
      parameters:
        - name: patientId
          in: path
          description: Patient ID
          required: true
          schema:
            type: string
      requestBody:
        description: Correct the patient properties to update.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      servers:
        - url: 'http://localhost:9001'
    delete:
      summary: Delete Patient Information
      description: Delete information for an existing patient.
      operationId: delete-patients-patientId
      parameters:
        - name: patientId
          in: path
          description: Patient ID
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      servers:
        - url: 'http://localhost:9001'
  /patients:
    post:
      summary: Create New Patient
      description: Create a new patient.
      operationId: post-patient
      requestBody:
        description: Post the necessary fields for the API to create a new patient.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      servers:
        - url: 'http://localhost:9001'
    get:
      summary: Get Patients Information
      description: Retrieve patient information.
      operationId: get-patients
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      servers:
        - url: 'http://localhost:9001'
components:
  schemas:
    Patient:
      type: object
      title: Patient
      properties:
        id:
          type: integer
          description: Unique identifier for the given patient.
        firstName:
          type: string
        lastName:
          type: string
        birthOfDate:
          type: string
          format: date
        gender:
          type: string
        address:
          type: string
        phoneNumber:
          type: string
        createName:
          type: string
          description: The username that created the patient.
        createDate:
          type: string
          description: The date the patient was created.
          format: date-time
        updateName:
          type: string
          description: The username who edited the patient.
        updateDate:
          type: string
          description: The date the patient was updated.
          format: date-time
      required:
        - firstName
        - lastName
        - birthOfDate
        - gender
    Error:
      type: object
      title: Error
      properties:
        code:
          type: string
        message:
          type: string
